---
title: "Gov 50 Final Project"
author: Lauren Alexes Kirkpatrick
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project Thoughts

I am interested in exploring data related to the relationship of race and what people choose to declare as a concentration at Harvard (or general majors across the country). As someone that has yet to declare, I feel as though that one's sense of "truly belonging" in a concentration (in regard to race) has influenced why people choose to study a particular field. 

## Proposal and Data

How do greater societal factors concerning identity sway an undergraduate's decision to declare a specific major? More specifically, how do race and income influence the major that post-secondary students decide to declare, or their ability to pursue a post-secondary degree in the first place? In the following project, I aim to explore the lack of diversity in specific academic fields across educational institutions within the United States. I hypothesize that the diversity of the faculty teaching influences a student's decision to declare a particular major, resulting in students of historically marginalized communities to declare majors that correlate with their identity (in relation to faculty or peers). Put simply, I believe that a lack of representation may deter a student from declaring a certain major, along with the income and race of that student having similar influence. 

Ultimately, I propose that there is a clear relationship between one's race, income, along with faculty diversity for a specific academic field, and the major a student declares in college. With a better understanding over how these variables impact one's decision to declare a particular field of study, we can then point to possibly WHY certain academic fields have a specific make-up of declared students (i.e. a racial or sex gap). My OUTCOME VARIABLE of interest is the NUMBER of students in each racial and sex group that DECLARE a particular major. Such ratios are measured from 1976-77 through 2020-21 by surveys conducted by the National Center for Education Statistics. My EXPLANATORY VARIABLES of interest would therefore be (1) the racial diversity in faculty for each major/academic field overtime from 2015 to 2016 (this data stems from an academic article, "Representation and Salary Gaps by Race-Ethnicity and Gender at Selective Public Universities" from SageJournals AND data from the National Center for Education Statistics [Full-time faculty in degree-granting post-secondary institutions, by race/ethnicity, sex, and academic rank: Fall 2019, fall 2020, and fall 2021]), along with (2) the identity of the students declaring said major (the students' RACE). 

To SUPPORT my thesis of race, income, and faculty diversity influencing what major one declares, there would need to be an observable correlation in values between the diversity of specific majors across race/income, and the diversity of faculty. In other words, if there were to be less Black students in one field of study, there would need to be less Black professors in this field. A direct reflection in values would illustrate how those of marginalized communities may deter from declaring a particular field of study that fails to be representative of their own identity. Thus, to DISPROVE my hypothesis, there would be NO observable inconsistent pattern/skew in data in regard to the race and income distribution across majors, and no shared pattern of racial/financial diversity with faculty. One would observe an even distribution of those of different races across the listed majors, along with a faculty unrepresentative of this distribution, demonstrating a LACK of correlation between the diversity of faculty and the diversity of those in a particular field. 

*As I have realized that cleaning up National Center for Education Statistics data tables is quite time consuming, I feel that it is a good first step to leverage the American Community Surveys of 2000 and 2020 (under the U.S. Census Bureau) in looking at the race, income, and educational achievement of individuals. This allows me to A) look for a relationship between income and race, along with progress overtime and B) have a baseline of how race or income impacts one's ability to pursue a post-secondary degree in the first place. Here, I will THEN be able to dig into how race plays a role in one's chosen field of study, along with one's income.

##One Interesting & Polished Data Visualization (The distribution of one variable or the relatinoship between two variables) 

```{r}
library(ggplot2)
library(tidyverse)
acs <- readRDS("acs.rds")

P1 <- ggplot(acs, aes(x = race, y = income)) + geom_jitter(size = .25, alpha = .1) + labs(title = "Race & Income", x = "Race of Respondent", y = "Income of Respondent")
P1
```
The above produces a data visualization that comments on the distribution of income among respondents of the 2000 American Community Survey (ACS) in regard to race. Besides creating another data visualization for the 2020 American Community Survey (for comparison and thus, progress), I hope to develop another data visualization that includes the race of post-secondary students in relation to these students' educational achievement (type of degree) and the field of study of said degree. This data visualization would be achieved through cleaning up the data cited by the National Center for Education Statistics. My hope is that I would be able to draw out a conclusion on the relationship between one's race/income and one's chosen field of study through comparing the two visualizations. 




